# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

# prevent executables from being installed
%global cargo_install_bin 0

%global crate nom-kconfig

Name:           rust-nom-kconfig
Version:        0.11.0
Release:        1%{?dist}
Summary:        Kconfig parser

License:        MIT
URL:            https://crates.io/crates/nom-kconfig
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  (crate(glob/default) >= 0.3.3 with crate(glob/default) < 0.4.0~)
BuildRequires:  (crate(nom/default) >= 8.0.0 with crate(nom/default) < 9.0.0~)
BuildRequires:  (crate(nom_locate/default) >= 5.0.0 with crate(nom_locate/default) < 6.0.0~)
BuildRequires:  (crate(serde/default) >= 1.0.228 with crate(serde/default) < 2.0.0~)
BuildRequires:  (crate(serde/derive) >= 1.0.228 with crate(serde/derive) < 2.0.0~)
BuildRequires:  rust >= 1.72
%if %{with check}
BuildRequires:  (crate(clap/default) >= 4.4.18 with crate(clap/default) < 5.0.0~)
BuildRequires:  (crate(clap/derive) >= 4.4.18 with crate(clap/derive) < 5.0.0~)
BuildRequires:  (crate(criterion/default) >= 0.5.1 with crate(criterion/default) < 0.6.0~)
BuildRequires:  (crate(criterion/html_reports) >= 0.5.1 with crate(criterion/html_reports) < 0.6.0~)
BuildRequires:  (crate(reqwest/blocking) >= 0.13.3 with crate(reqwest/blocking) < 0.14.0~)
BuildRequires:  (crate(reqwest/default) >= 0.13.3 with crate(reqwest/default) < 0.14.0~)
BuildRequires:  (crate(tracing-subscriber/default) >= 0.3.23 with crate(tracing-subscriber/default) < 0.4.0~)
BuildRequires:  (crate(walkdir/default) >= 2.5.0 with crate(walkdir/default) < 3.0.0~)
%endif

%global _description %{expand:
A Kconfig parser.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch
Provides:       crate(nom-kconfig) = 0.11.0
Requires:       (crate(nom/default) >= 8.0.0 with crate(nom/default) < 9.0.0~)
Requires:       (crate(nom_locate/default) >= 5.0.0 with crate(nom_locate/default) < 6.0.0~)
Requires:       cargo
Requires:       rust >= 1.72

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch
Provides:       crate(nom-kconfig/default) = 0.11.0
Requires:       cargo
Requires:       crate(nom-kconfig) = 0.11.0
Requires:       crate(nom-kconfig/deserialize) = 0.11.0
Requires:       crate(nom-kconfig/display) = 0.11.0
Requires:       crate(nom-kconfig/hash) = 0.11.0
Requires:       crate(nom-kconfig/kconfiglib) = 0.11.0
Requires:       crate(nom-kconfig/serialize) = 0.11.0

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+coreboot-devel
Summary:        %{summary}
BuildArch:      noarch
Provides:       crate(nom-kconfig/coreboot) = 0.11.0
Requires:       (crate(glob/default) >= 0.3.3 with crate(glob/default) < 0.4.0~)
Requires:       cargo
Requires:       crate(nom-kconfig) = 0.11.0
Requires:       crate(nom-kconfig/named-choice) = 0.11.0

%description -n %{name}+coreboot-devel %{_description}

This package contains library source intended for building other packages which
use the "coreboot" feature of the "%{crate}" crate.

%files       -n %{name}+coreboot-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+debug-devel
Summary:        %{summary}
BuildArch:      noarch
Provides:       crate(nom-kconfig/debug) = 0.11.0
Requires:       (crate(tracing/default) >= 0.1.44 with crate(tracing/default) < 0.2.0~)
Requires:       (crate(tracing/log) >= 0.1.44 with crate(tracing/log) < 0.2.0~)
Requires:       cargo
Requires:       crate(nom-kconfig) = 0.11.0

%description -n %{name}+debug-devel %{_description}

This package contains library source intended for building other packages which
use the "debug" feature of the "%{crate}" crate.

%files       -n %{name}+debug-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+deserialize-devel
Summary:        %{summary}
BuildArch:      noarch
Provides:       crate(nom-kconfig/deserialize) = 0.11.0
Requires:       (crate(serde/default) >= 1.0.228 with crate(serde/default) < 2.0.0~)
Requires:       (crate(serde/derive) >= 1.0.228 with crate(serde/derive) < 2.0.0~)
Requires:       cargo
Requires:       crate(nom-kconfig) = 0.11.0

%description -n %{name}+deserialize-devel %{_description}

This package contains library source intended for building other packages which
use the "deserialize" feature of the "%{crate}" crate.

%files       -n %{name}+deserialize-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+display-devel
Summary:        %{summary}
BuildArch:      noarch
Provides:       crate(nom-kconfig/display) = 0.11.0
Requires:       cargo
Requires:       crate(nom-kconfig) = 0.11.0

%description -n %{name}+display-devel %{_description}

This package contains library source intended for building other packages which
use the "display" feature of the "%{crate}" crate.

%files       -n %{name}+display-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hash-devel
Summary:        %{summary}
BuildArch:      noarch
Provides:       crate(nom-kconfig/hash) = 0.11.0
Requires:       cargo
Requires:       crate(nom-kconfig) = 0.11.0

%description -n %{name}+hash-devel %{_description}

This package contains library source intended for building other packages which
use the "hash" feature of the "%{crate}" crate.

%files       -n %{name}+hash-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+kconfiglib-devel
Summary:        %{summary}
BuildArch:      noarch
Provides:       crate(nom-kconfig/kconfiglib) = 0.11.0
Requires:       (crate(glob/default) >= 0.3.3 with crate(glob/default) < 0.4.0~)
Requires:       cargo
Requires:       crate(nom-kconfig) = 0.11.0
Requires:       crate(nom-kconfig/named-choice) = 0.11.0

%description -n %{name}+kconfiglib-devel %{_description}

This package contains library source intended for building other packages which
use the "kconfiglib" feature of the "%{crate}" crate.

%files       -n %{name}+kconfiglib-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+named-choice-devel
Summary:        %{summary}
BuildArch:      noarch
Provides:       crate(nom-kconfig/named-choice) = 0.11.0
Requires:       cargo
Requires:       crate(nom-kconfig) = 0.11.0

%description -n %{name}+named-choice-devel %{_description}

This package contains library source intended for building other packages which
use the "named-choice" feature of the "%{crate}" crate.

%files       -n %{name}+named-choice-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serialize-devel
Summary:        %{summary}
BuildArch:      noarch
Provides:       crate(nom-kconfig/serialize) = 0.11.0
Requires:       (crate(serde/default) >= 1.0.228 with crate(serde/default) < 2.0.0~)
Requires:       (crate(serde/derive) >= 1.0.228 with crate(serde/derive) < 2.0.0~)
Requires:       cargo
Requires:       crate(nom-kconfig) = 0.11.0

%description -n %{name}+serialize-devel %{_description}

This package contains library source intended for building other packages which
use the "serialize" feature of the "%{crate}" crate.

%files       -n %{name}+serialize-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
