# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

# prevent executables from being installed
%global cargo_install_bin 0

%global crate nom-kconfig

Name:           rust-nom-kconfig
Version:        0.12.0
Release:        1%{?dist}
Summary:        Kconfig parser

License:        MIT
URL:            https://crates.io/crates/nom-kconfig
Source:         %{crates_source}
# Remove the criterion dev-dependency and the bench target that needs it,
# since criterion is not packaged in Fedora.
Patch:          nom-kconfig-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
A Kconfig parser.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+debug-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debug-devel %{_description}

This package contains library source intended for building other packages which
use the "debug" feature of the "%{crate}" crate.

%files       -n %{name}+debug-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+deserialize-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+deserialize-devel %{_description}

This package contains library source intended for building other packages which
use the "deserialize" feature of the "%{crate}" crate.

%files       -n %{name}+deserialize-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+display-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+display-devel %{_description}

This package contains library source intended for building other packages which
use the "display" feature of the "%{crate}" crate.

%files       -n %{name}+display-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glob-wildcard-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glob-wildcard-devel %{_description}

This package contains library source intended for building other packages which
use the "glob-wildcard" feature of the "%{crate}" crate.

%files       -n %{name}+glob-wildcard-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hash-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hash-devel %{_description}

This package contains library source intended for building other packages which
use the "hash" feature of the "%{crate}" crate.

%files       -n %{name}+hash-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+kconfiglib-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+kconfiglib-devel %{_description}

This package contains library source intended for building other packages which
use the "kconfiglib" feature of the "%{crate}" crate.

%files       -n %{name}+kconfiglib-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+named-choice-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+named-choice-devel %{_description}

This package contains library source intended for building other packages which
use the "named-choice" feature of the "%{crate}" crate.

%files       -n %{name}+named-choice-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serialize-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serialize-devel %{_description}

This package contains library source intended for building other packages which
use the "serialize" feature of the "%{crate}" crate.

%files       -n %{name}+serialize-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
