name: Tag

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"
  RUSTDOCFLAGS: '--deny warnings'
  MINIMUM_SUPPORTED_RUST_VERSION: 1.80.1
  RUST_CHANNEL: stable


permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - CHANGELOG.md

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      created: ${{ steps.tag.outputs.created }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
        with:
          persist-credentials: false
      - name: Get tags
        run: git fetch --tags origin
      - name: Install Rust
        run: |
          rustup update --no-self-update ${RUST_CHANNEL}
          rustup component add --toolchain ${RUST_CHANNEL} cargo
          rustup default ${RUST_CHANNEL}
        env:
          RUST_CHANNEL: ${{ env.RUST_CHANNEL }}
      
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # ratchet:Swatinem/rust-cache@v2
      - name: Configure git
        run: |
          git config --global user.name "$NAME"
          git config --global user.email "$EMAIL"
          git config --global push.autoSetupRemote true
      - name: Get the version
        id: current
        run: echo "version=$(cargo pkgid | cut -d '#' -f2)" >> "$GITHUB_OUTPUT"
      - name: Create git tag
        id: tag
        run: |
          if git tag -a "v${VERSION}" -m "${VERSION}"; then
            echo "created=true" >> "$GITHUB_OUTPUT"
          else
            echo "::notice title=Git tag:: The version ${VERSION} already exists. The \`publish\` workflow won't be executed."
            echo "created=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          VERSION: ${{ steps.current.outputs.version }}
          NAME: ${{ github.actor }}
          EMAIL: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com


  publish:
    needs: tag
    if: ${{ needs.tag.outputs.created == 'true' }}
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    permissions:
      contents: write
      actions: write
      packages: write
      attestations: write
      id-token: write
      pull-requests: write
      artifact-metadata: write
